apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # echo -n "mon_secret_jwt_tres_long_a_changer_en_prod" | base64
  JWT_SECRET: bW9uX3NlY3JldF9qd3RfdHJlc19sb25nX2FfY2hhbmdlcl9lbl9wcm9k
