apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # echo -n "authdb" | base64
  MONGO_DB: YXV0aGRi
  # echo -n "mongodb://mongodb:27017/authdb" | base64
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvYXV0aGRi
