apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Valeurs encodees en base64.
  # En production : utiliser AWS Secrets Manager / HashiCorp Vault.
  # echo -n "etudiantsdb" | base64 -> ZXR1ZGlhbnRzZGI=
  POSTGRES_DB: ZXR1ZGlhbnRzZGI=
  # echo -n "postgres" | base64 -> cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  # echo -n "password" | base64 -> cGFzc3dvcmQ=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
