apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "projet-etudiants.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secrets.postgres.db }}
  POSTGRES_USER: {{ .Values.secrets.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  labels:
    {{- include "projet-etudiants.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwt.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    {{- include "projet-etudiants.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_URI: {{ .Values.secrets.mongodb.uri }}
