apiVersion: v1
kind: Service
metadata:
  name: etudiant-service
  labels:
    app: etudiant-service
spec:
  selector:
    app: etudiant-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
