---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: etudiants
            - name: POSTGRES_USER
              value: etudiants
            - name: POSTGRES_PASSWORD
              value: etudiants
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "etudiants"]
            initialDelaySeconds: 10
            periodSeconds: 5
